# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY pyproject.toml pyproject.toml
COPY uv.lock uv.lock
COPY src src

# Upgrade pip and install project
RUN pip install --upgrade pip && \
    pip install .

# Default command
ENTRYPOINT ["blender-mcp"]
